# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd618e324d7be366e6c1ae46f89a672195595faac358f3ee808e7aafd6ab6db602903bf10362a6f1452d2e80c64cab5ed672d394b1d5c70f76953ecd3d1af554

test:
  secret_key_base: 86acd7dc94e05c56c773e077ee9c34b9d6a5e91f4b01d29dac7faa70c95b08a812f092dae17f9c25d12c28b6b3d9e100a18f6922ef0e25685618b5bb696aad11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
